name: tofo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_auth: ^4.15.2
  font_awesome_flutter: ^9.1.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  google_sign_in: ^6.1.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  tflite_v2: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/facebook_logo.png
    - assets/login.png
    - 'assets/back.jpg'

