// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpQeYwgUtRruF-WvOXhliGnSIydCZEgaY',
    appId: '1:441789180844:web:debf542497d6ed9b3e6809',
    messagingSenderId: '441789180844',
    projectId: 'todo-d0493',
    authDomain: 'todo-d0493.firebaseapp.com',
    storageBucket: 'todo-d0493.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RuA34mtsvvVa4Y3UcD1_qu5SoZErSMk',
    appId: '1:441789180844:android:ab7b2bf0fef895af3e6809',
    messagingSenderId: '441789180844',
    projectId: 'todo-d0493',
    storageBucket: 'todo-d0493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMUbhwrfWFatxyUYJ0K8h_fG1u--o43OQ',
    appId: '1:441789180844:ios:df76dcb8d36eed893e6809',
    messagingSenderId: '441789180844',
    projectId: 'todo-d0493',
    storageBucket: 'todo-d0493.appspot.com',
    iosBundleId: 'com.example.tofo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMUbhwrfWFatxyUYJ0K8h_fG1u--o43OQ',
    appId: '1:441789180844:ios:bbd382ee36bf42c63e6809',
    messagingSenderId: '441789180844',
    projectId: 'todo-d0493',
    storageBucket: 'todo-d0493.appspot.com',
    iosBundleId: 'com.example.tofo.RunnerTests',
  );
}
